### ISSUE TITLE
Add link to RFC

### ISSUE THREAD

**Issue by Beau-Gosse-dev** [karlospn/deploy-dotnet-lambda-with-aws-cdk#1]
Hello! 

There is actually an RFC to better support .NET Lambdas in CDK. It will automatically package your code given only a path to the project. It would be great if you could update your blog or repo asking people to try it out and leave comments so that we can hopefully get it officially merged. 

https://github.com/aws/aws-cdk-rfcs/issues/469

**Comment by karlospn** [comment]
> Hello!
> 
> There is actually an RFC to better support .NET Lambdas in CDK. It will automatically package your code given only a path to the project. It would be great if you could update your blog or repo asking people to try it out and leave comments so that we can hopefully get it officially merged.
> 
> [aws/aws-cdk-rfcs#469](https://github.com/aws/aws-cdk-rfcs/issues/469)

Hi there! I just took a quick glance at the RFC, but it looks promising. 

I'll try to spend some time messing around with it next week. If it works well, I'd be happy to update the post with this new deployment option. Also, I'll use this as an excuse to update the post source code to .NET 6 and .NET 7.

Would be nice having an easier way to deplay a .NET lambda. Happy to help wherever I can.

**Comment by karlospn** [comment]
Done!
- https://www.mytechramblings.com/posts/deploy-dotnet-lambdas-with-aws-cdk/
